spring:
  application:
    name: org.cameek.spring_excel
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:metrics.db
    username: 
    password: 
    
excel:
  template: src/main/resources/template.xlsx
  output: report-output.xlsx

report:
  start-date: '2025-01-01'
  end-date: '2025-12-31'
